---
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
      time: "12:00"
      timezone: America/Los_Angeles
    assignees:
      - grayespinoza
    commit-message:
      prefix: chore
